### ISSUE TITLE
Split Index

### ISSUE THREAD

**Issue by Voroniyx** [discordexperimenthub/deh-bot#5]
It would give a much better overview if you move all the events from index.js to an event folder and move all the other functions to `src/modules` or create a new folder: `src/util`. Because currently the index.js with more than 1.5K lines is quite confusing.

![image](https://github.com/discordexperimenthub/deh-bot/assets/91881990/f90e2762-e86d-454f-9fb0-cf0ee544bdbc)

And how did you feel about writing the project in typescript at some point?

**Comment by xHyroM** [comment]
We can do listeners handler (like command handler) and put them into `listener(s)/XXXX.js` and then have code changes, etc in `modules/`

**Comment by Voroniyx** [comment]
this would also be a variant

**Comment by Voroniyx** [comment]
@Tolga1452 what do want to say to this issue?

**Comment by Tolga1452** [comment]
> @Tolga1452 what do want to say to this issue?

i will take a look but not yet

**Comment by xHyroM** [comment]
looks like not planned
